# Generated by Django 3.1.6 on 2021-02-16 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_auto_20210216_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customusermodel',
            old_name='mobile',
            new_name='phone_number',
        ),
    ]
