# Generated by Django 3.1.6 on 2021-02-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_auto_20210216_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModelTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=60, unique=True)),
                ('username', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
            ],
        ),
    ]
