# Generated by Django 3.1.6 on 2021-02-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_usermodeltest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
