# Generated by Django 3.1.6 on 2021-02-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_auto_20210219_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='email',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='username',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
